def on_forever():
    basic.show_string("Shalom")
    basic.clear_screen()
    basic.pause(500)
    basic.show_string("8F")
    basic.clear_screen()
    basic.pause(500)
    basic.show_icon(IconNames.HEART)
    basic.clear_screen()
    basic.pause(500)
    basic.show_icon(IconNames.SMALL_HEART)
    basic.clear_screen()
    basic.pause(500)
basic.forever(on_forever)