basic.forever(function on_forever() {
    basic.showString("Shalom")
    basic.clearScreen()
    basic.pause(500)
    basic.showString("8F")
    basic.clearScreen()
    basic.pause(500)
    basic.showIcon(IconNames.Heart)
    basic.clearScreen()
    basic.pause(500)
    basic.showIcon(IconNames.SmallHeart)
    basic.clearScreen()
    basic.pause(500)
})
